//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webmarktingcopy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_registration
    {
        public int Id { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
        public string Re_Password { get; set; }
        public string Mobile_n { get; set; }
        public string Country { get; set; }
        public string Gender { get; set; }
        public string Company_Name { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string Postal_code { get; set; }
    }
}
